# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/tykn-ssi-services/*'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/tykn-ssi-services/*'

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: CmdLine@2
    inputs:
      workingDirectory: services/tykn-ssi-services/
      script: echo "Hello World!"
