
# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android

variables:
  workingDir: interfaces/AW-App/


trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/AW-App/*'
pr:
  branches:
    include:
    - master
    - native/*
    - android/*
  paths:
    include:
    - 'interfaces/AW-App/*'


pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm ci
  displayName: Install
  workingDirectory: $(workingDir)

- script: npm run ionic -- cordova resources android
  displayName: 'Generate Assests'
  workingDirectory: $(workingDir)

- script: echo 'Set Environment variables' && printenv
  displayName: 'Set Environment variables - Debug'
  workingDirectory: $(workingDir)
  env:
    NG_PRODUCTION: $(ng_production)
    NG_IS_DEBUG: $(ng_is_debug)
    NG_SHOW_DEBUG: $(ng_show_debug)
    NG_USE_ANIMATION: $(ng_use_animation)
    NG_URL_121_SERVICE_API: $(test_ng_url_121_service_api)

- script: npm run build:native -- --prod
  displayName: 'Build Android APK - Debug'
  workingDirectory: $(workingDir)

- script: echo 'Set Environment variables' && printenv
  displayName: 'Set Environment variables - Production'
  workingDirectory: $(workingDir)
  env:
    NG_PRODUCTION: $(ng_production)
    NG_IS_DEBUG: $(ng_is_debug)
    NG_SHOW_DEBUG: $(ng_show_debug)
    NG_USE_ANIMATION: $(ng_use_animation)
    NG_URL_121_SERVICE_API: $(production_ng_url_121_service_api)

- script: npm run build:native -- --prod --release
  displayName: 'Build Android APK - Production'
  workingDirectory: $(workingDir)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: interfaces/AW-App/platforms/android/app/build/outputs/apk/
    artifactName: 'AW-App'
