trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/AW-App/*'


pool:
  vmImage: 'macOS-10.14'

steps:
- script: echo Starting build

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm ci
  displayName: Install
  workingDirectory: interfaces/AW-App/

- script: npm run ionic -- cordova resources android
  displayName: GenerateAssest
  workingDirectory: interfaces/AW-App/

- script: npm run build:native --debug
  displayName: BuildAndroid
  workingDirectory: interfaces/AW-App/

- script: npm run build:native -- --prod
  displayName: BuildAndroidProd
  workingDirectory: interfaces/AW-App/

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: interfaces/AW-App/platforms/android/app/build/outputs/apk/
    artifactName: 'AW-app'




