
# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/AW-App/*'
pr:
  branches:
    include:
    - native*
    - android*
  paths:
    include:
    - 'interfaces/AW-App/*'


pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm ci
  displayName: Install
  workingDirectory: interfaces/AW-App/

- script: npm run ionic -- cordova resources android
  displayName: GenerateAssest
  workingDirectory: interfaces/AW-App/

- script: npm run build:native --debug
  displayName: BuildAndroid
  workingDirectory: interfaces/AW-App/

- script: npm run build:native -- --prod -- --release
  displayName: BuildAndroidProd
  workingDirectory: interfaces/AW-App/

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: interfaces/AW-App/platforms/android/app/build/outputs/apk/
    artifactName: 'AW-app'




