version: '3.7'

services:
  indypool:
    build:
      context: tykn-ssi-services 
      dockerfile: indy-pool.dockerfile
      args:
        pool_ip: '11.0.0.2'
    init: true
    container_name: tykn_indy_pool
    healthcheck:
      test: "exit 0"
    ports:
      - "9701:9701"
      - "9702:9702"
      - "9703:9703"
      - "9704:9704"
      - "9705:9705"
      - "9706:9706"
      - "9707:9707"
      - "9708:9708"
    networks:
      pool_network:
        ipv4_address: 11.0.0.2
  tyknims:
    build: 
      context: tykn-ssi-services/TyknIMS  
      dockerfile: Dockerfile
    init: true
    container_name: tyknims
    ports:
      - "50001:50001"
    networks:
      pool_network:
        ipv4_address: 11.0.0.3
    healthcheck:
      test: "exit 0"
    depends_on:
      - indypool
    links:
      - indypool
  orgims:
    build:
      context: tykn-ssi-services/OrgIMS  
      dockerfile: Dockerfile
      args:
        - CONFIG=config.json
    init: true
    container_name: orgims
    ports:
      - "50002:50002"
    healthcheck:
      test: "exit 0"
    restart: on-failure
    networks:
      pool_network:
        ipv4_address: 11.0.0.4
    depends_on:
      - indypool
      - tyknims
    links:
      - indypool
      - tyknims
  userims:
    build: 
      context: tykn-ssi-services/UserIMS 
      dockerfile: Dockerfile
    init: true
    container_name: userims
    healthcheck:
      test: "exit 0"
    restart: on-failure
    ports:
      - "50003:50003"
    networks:
      pool_network:
        ipv4_address: 11.0.0.5
    depends_on:
      - indypool
      - tyknims
    links:
      - indypool
  121db:
    image: "postgres:9.6"
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=global121
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=global121
    volumes:
      - "./postgresql.conf:/etc/postgresql.conf"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5438:5432"
    restart: always
    networks:
      pool_network:
        ipv4_address: 11.0.0.6
  121-service:
    build: 
      context: 121-service
      dockerfile: Dockerfile
    init: true
    container_name: 121-service
    volumes: 
      - "./121-service:/home/121/services/121-service"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: 11.0.0.7
  PA-accounts-service:
    build:
      context: PA-accounts-service
      dockerfile: Dockerfile
    image: pa-accounts-node
    init: true
    container_name: PA-accounts-service
    volumes:
      - "./PA-accounts-service:/home/121/services/PA-accounts-service"
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: 11.0.0.8

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24