# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - services/programs-service/*

pr:
  branches:
    include:
    - "*"
  paths:
    include:
    - services/programs-service/*

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: npm install
  displayName: Install
  workingDirectory: services/programs-service/

- script: npm test
  displayName: Tests
  workingDirectory: services/programs-service/
