# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - greenkeeper/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - 'services/programs-service/*'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: CmdLine@2
  inputs:
    script: cp services/programs-service/src/secrets.ts.example services/programs-service/src/secrets.ts

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm ci
  displayName: Install
  workingDirectory: services/programs-service/

- script: npm test
  displayName: Tests
  workingDirectory: services/programs-service/
