# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - greenkeeper/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/HO-Portal/*'

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: npm ci
  displayName: Install
  workingDirectory: interfaces/HO-Portal/

- script: npm run lint
  displayName: Linting
  workingDirectory: interfaces/HO-Portal/

- script: npm test
  displayName: Tests
  workingDirectory: interfaces/HO-Portal/

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
