# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - interfaces/HO-Portal/*

pr:
  branches:
    include:
    - "*"
  paths:
    include:
    - interfaces/HO-Portal/*

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: npm install
  displayName: Install
  workingDirectory: interfaces/HO-Portal/

- script: npm run lint
  displayName: Linting
  workingDirectory: interfaces/HO-Portal/

- script: npm run test:ci
  displayName: Tests
  workingDirectory: interfaces/HO-Portal/

- script: npm run build -- --prod
  displayName: Build
  workingDirectory: interfaces/HO-Portal/

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
